"""add enrichment cache constraints

Revision ID: 86bf5d6b6ace
Revises: 6c644d70576a
Create Date: 2026-07-25 06:27:06.113344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bf5d6b6ace'
down_revision: Union[str, Sequence[str], None] = '6c644d70576a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrichments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_enrichment_ioc_provider', 'enrichments', ['ioc_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_enrichment_ioc_provider', 'enrichments', type_='unique')
    op.drop_column('enrichments', 'updated_at')
    # ### end Alembic commands ###
