"""create iocs table

Revision ID: c329fa1b9622
Revises: 80e05e311bb3
Create Date: 2026-07-21 12:23:48.830583

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c329fa1b9622'
down_revision: str | Sequence[str] | None = '80e05e311bb3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
