"""add report metadata

Revision ID: ceef84241b62
Revises: e1080f674dc6
Create Date: 2026-08-06 13:12:58.916940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceef84241b62'
down_revision: Union[str, Sequence[str], None] = 'e1080f674dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "reports",
        sa.Column(
            "report_type",
            sa.String(),
            nullable=False,
            server_default="IOC Intelligence",
        ),
    )

    op.add_column(
        "reports",
        sa.Column(
            "created_by",
            sa.String(),
            nullable=False,
            server_default="ThreatFusion",
        ),
    )

    # Optional cleanup: remove database defaults after existing rows are updated
    op.alter_column(
        "reports",
        "report_type",
        server_default=None,
    )

    op.alter_column(
        "reports",
        "created_by",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'created_by')
    op.drop_column('reports', 'report_type')
    # ### end Alembic commands ###
